# Used to run with Docker CLI, run command: docker-compose up --build OR can just use the local docker containers
# Docker Compose configuration for Patient Service and PostgreSQL database

services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - patient-service-data:/var/lib/postgresql/data
    ports:
      - "5200:5432"
    networks:
      - internal

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
    depends_on:
      - patient-service-db
    ports:
      - "4000:4000"
    networks:
      - internal

volumes:
  patient-service-data:

# !!! Make sure the network 'internal' is created before running the services !!!
networks:
  internal:
    external: true
