### POST Create Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Sam kafka consumer test",
    "email": "samkafka@gmail.com",
    "address": "123 Street, City, Country",
    "dateOfBirth": "1990-01-01",
    "registeredDate": "2023-10-01"
}

###